drop table if exists authors CASCADE ;
drop table if exists book_categories CASCADE ;
drop table if exists book_category_relation CASCADE ;
drop table if exists books CASCADE ;


    create table authors (
       author_id bigint generated by default as identity,
        firstname varchar(255) not null,
        lastname varchar(255) not null,
        nickname varchar(255),
        primary key (author_id)
    );


    create table book_categories (
       book_category_id bigint generated by default as identity,
        book_category_name varchar(255) not null,
        primary key (book_category_id)
    );


    create table book_category_relation (
       book_id bigint not null,
        book_category_id bigint not null
    );


    create table books (
       book_id bigint generated by default as identity,
        title varchar(255) not null,
        author_id bigint,
        primary key (book_id)
    );
    create table notes (
           note_id bigint generated by default as identity,
            comment varchar(255) not null,
            book_id bigint,
            primary key (note_id)
        );
alter table notes
       add constraint FK_n_book_id
       foreign key (book_id)
       references books;

    alter table book_categories
       add constraint UK_qeaemj9nf6y2n9sgx3xba152b unique (book_category_name);





    
    alter table books 
       add constraint fk_author_id 
       foreign key (author_id) 
       references authors;